FROM mhart/alpine-node:4.4.7

MAINTAINER Thomas Delaet <thomas@delaet.org>

ENV CODE_DIR /root/dht
RUN mkdir ${CODE_DIR}

COPY ./index.js ${CODE_DIR}
COPY ./package.json ${CODE_DIR}
COPY ./bin/mm-dht ${CODE_DIR}

WORKDIR ${CODE_DIR}
RUN npm install

ENV STORAGE_DIR /tmp

CMD ["${CODE_DIR}/bin/mm-dht"]
