#!/bin/bash

VERSION='0.1'
WHAT_AM_I=$(uname -m)
IMAGE_RPI='nocloud/kadserver-rpi'
IMAGE_x86='nocloud/kadserver-x86'

# Exit upon errors
set -e

function log_info {
  if [ "$QUIET" == "" ]; then
    echo -e "`basename $0`: [\e[32mINFO\e[0m] " $1
  fi
}

function log_warn {
  echo -e "`basename $0`: [\e[33mWARN\e[0m] " $1
}

function log_fatal {
  echo -e "`basename $0`: [\e[31mFATAL\e[0m] " $1
  exit 1
}

function build {
  if [ "$WHAT_AM_I" == "armv6l" ]; then
    build4rpi
  else
    build4x86
  fi
}

function build4rpi {
  log_info "Building docker container to run kad server on rpi"
  cp ./Dockerfile.rpi ../Dockerfile
  pushd ../. >> /dev/null
  docker build -t ${IMAGE_RPI} .
  popd >> /dev/null
  rm ../Dockerfile
  log_info "Done"
}

function build4x86 {
  log_info "Building docker container to run kad server on x86"
  cp ./Dockerfile.x86 ../Dockerfile
  pushd ../. >> /dev/null
  docker build -t ${IMAGE_x86} .
  popd >> /dev/null
  rm ../Dockerfile
  log_info "Done"
}

# Prints out usage information
#
function usage {
cat << END
Control script for building kad server container $VERSION
Usage: build
END
exit 0
}

build
