#!/bin/bash

VERSION='0.1'
WHAT_AM_I=$(uname -m)
IMAGE_RPI='nocloud/rpi-kadserver'
IMAGE_x86='nocloud/kadserver'
CMD="./start.sh $@"

echo $CMD

# Exit upon errors
set -e

function log_info {
  if [ "$QUIET" == "" ]; then
    echo -e "`basename $0`: [\e[32mINFO\e[0m] " $1
  fi
}

function log_warn {
  echo -e "`basename $0`: [\e[33mWARN\e[0m] " $1
}

function log_fatal {
  echo -e "`basename $0`: [\e[31mFATAL\e[0m] " $1
  exit 1
}

function run {
  if [ "$WHAT_AM_I" == "armv6l" ]; then
    log_info "Launching kad server container on rpi"
    docker run --net=host -d $IMAGE_RPI $CMD
  else
    log_info "Launching kad server container on x86"   
    docker run --net=host -d $IMAGE_x86 $CMD
  fi
}

# Prints out usage information
#
function usage {
cat << END
Control script for launching kad server container $VERSION
Usage: run options
END
exit 0
}

run
